module.exports = {
    PORT: 5001,
    BASE_PATH: '/webApi/fxLot',
    BASE_CURRENCY: 'USD',
    CACHE_EXPIRE_SEC: 60*120,
    POLL_INTERVAL: 1000*60*3,
    CORRELATION_THRESH: 50,
    NEUTRAL_CORRELATION_THRESH: 25,
    UNBALANCED_CORRELATION_THRESH: 40,
    PAIR_ID: {
        AUDCAD: 8,
        AUDCHF: 47,
        AUDJPY: 9,
        AUDNZD: 10,
        AUDUSD: 11,
        CADCHF: 103,
        CADJPY: 12,
        CHFJPY: 46,
        EURAUD: 6,
        EURCAD: 13,
        EURCHF: 14,
        EURGBP: 17,
        EURJPY: 7,
        EURNZD: 20,
        EURUSD: 1,
        GBPAUD: 107,
        GBPCAD: 24,
        GBPCHF: 25,
        GBPJPY: 4,
        GBPNZD: 48,
        GBPUSD: 27,
        NZDCAD: 49,
        NZDCHF: 26,
        NZDJPY: 2,
        NZDUSD: 28,
        USDCAD: 5,
        USDCHF: 29,
        USDJPY: 3,
    },
    AUTO_FETCH_PAIRS: ['EURUSD', 'EURCAD', 'EURNZD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURSGD', 'EURAUD'],
    ACCOUNT_TYPE: 'Standard',
}